const db = require("../db");

let rideMessagesTableReady = false;

async function ensureRideMessagesTable() {
  if (rideMessagesTableReady) {
    return;
  }

  await db.query(`
    CREATE TABLE IF NOT EXISTS ride_messages (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ride_id integer NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
      sender_id integer NOT NULL,
      sender_role varchar(20) NOT NULL CHECK (sender_role IN ('Consumer', 'Driver')),
      message_type varchar(20) NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'system')),
      body text NOT NULL CHECK (length(btrim(body)) > 0),
      client_message_id varchar(100),
      created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
      delivered_at timestamp without time zone,
      read_at timestamp without time zone,
      UNIQUE (ride_id, sender_id, client_message_id)
    )
  `);

  await db.query(`
    CREATE INDEX IF NOT EXISTS idx_ride_messages_ride_created
    ON ride_messages (ride_id, created_at)
  `);

  rideMessagesTableReady = true;
}

function serializeRideMessage(row) {
  return {
    id: row.id,
    rideId: row.ride_id,
    senderId: row.sender_id,
    senderRole: row.sender_role,
    messageType: row.message_type,
    body: row.body,
    clientMessageId: row.client_message_id,
    createdAt: row.created_at,
    deliveredAt: row.delivered_at || null,
    readAt: row.read_at || null,
  };
}

async function findExistingRideMessage(rideId, senderId, clientMessageId) {
  await ensureRideMessagesTable();

  if (!clientMessageId) {
    return null;
  }

  const existing = await db.query(
    `SELECT id, ride_id, sender_id, sender_role, message_type, body, client_message_id, created_at, delivered_at, read_at
     FROM ride_messages
     WHERE ride_id = $1 AND sender_id = $2 AND client_message_id = $3
     ORDER BY created_at DESC
     LIMIT 1`,
    [rideId, senderId, clientMessageId]
  );

  return existing.rows[0] || null;
}

async function persistRideMessage({ rideId, senderId, senderRole, messageType, body, clientMessageId = null }) {
  await ensureRideMessagesTable();

  const existing = await findExistingRideMessage(rideId, senderId, clientMessageId);
  if (existing) {
    return { inserted: false, message: serializeRideMessage(existing) };
  }

  try {
    const result = await db.query(
      `INSERT INTO ride_messages (ride_id, sender_id, sender_role, message_type, body, client_message_id)
       VALUES ($1, $2, $3, $4, $5, $6)
       RETURNING id, ride_id, sender_id, sender_role, message_type, body, client_message_id, created_at, delivered_at, read_at`,
      [rideId, senderId, senderRole, messageType, body, clientMessageId]
    );

    return { inserted: true, message: serializeRideMessage(result.rows[0]) };
  } catch (error) {
    // If the database enforces uniqueness on client_message_id, return the
    // original row instead of surfacing a duplicate-send failure.
    if (clientMessageId && error?.code === "23505") {
      const duplicate = await findExistingRideMessage(rideId, senderId, clientMessageId);
      if (duplicate) {
        return { inserted: false, message: serializeRideMessage(duplicate) };
      }
    }

    throw error;
  }
}

module.exports = {
  ensureRideMessagesTable,
  persistRideMessage,
  serializeRideMessage,
};
